export const adidasProducts =[
    {
        id: "adidas1",
        name: 'Adidas ',
        price: 130,
        image: '../public/addidas/adidas (1).png',
        alt:"Adidas",
        rating: 3.9,
        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-500' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas2",
        name: 'Adidas ',
        price: 330,
        image: '../public/addidas/adidas (2).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas3",
        name: 'Adidas ',
        price: 350,
        image: '../public/addidas/adidas (3).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas4",
        name: 'Adidas ',
        price: 130,
        image: '../public/addidas/adidas (4).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas5",
        name: 'Adidas ',
        price: 300,
        image: '../public/addidas/adidas (5).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas6",
        name: 'Adidas ',
        price: 300,
        image: '../public/addidas/adidas (6).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas7",
        name: 'Adidas ',
        price: 350,
        image: '../public/addidas/adidas (7).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas8",
        name: 'Adidas ',
        price: 321,
        image: '../public/addidas/adidas (8).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas9",
        name: 'Adidas ',
        price: 231,
        image: '../public/addidas/adidas (9).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas10",
        name: 'Adidas ',
        price: 243,
        image: '../public/addidas/adidas (10).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas11",
        name: 'Adidas ',
        price: 13,
        image: '../public/addidas/adidas (11).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas12",
        name: 'Adidas ',
        price: 65,
        image: '../public/addidas/adidas (12).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ], 
    },
    {
        id: "adidas13",
        name: 'Adidas ',
        price: 240,
        image: '../public/addidas/adidas (13).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas14",
        name: 'Adidas ',
        price: 187,
        image: '../public/addidas/adidas (14).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas15",
        name: 'Adidas ',
        price: 136,
        image: '../public/addidas/adidas (15).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas16",
        name: 'Adidas ',
        price: 120,
        image: '../public/addidas/adidas (16).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas17",
        name: 'Adidas ',
        price: 130,
        image: '../public/addidas/adidas (17).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas18",
        name: 'Adidas ',
        price: 160,
        image: '../public/addidas/adidas (18).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas19",
        name: 'Adidas ',
        price: 130,
        image: '../public/addidas/adidas (19).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas20",
        name: 'Adidas ',
        price: 190,
        image: '../public/addidas/adidas (20).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas21",
        name: 'Adidas ',
        price: 110,
        image: '../public/addidas/adidas (21).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas22",
        name: 'Adidas ',
        price: 1330,
        image: '../public/addidas/adidas (22).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
    {
        id: "adidas23",
        name: 'Adidas ',
        price: 150,
        image: '../public/addidas/adidas (23).png',
        rating: 3.9,
        alt:"Adidas",

        reviewCount: 117,
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
          ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
          ],
    },
]
export const nikeProducts =[
    {
        id: "nike1",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (1).png',
    },
    {
        id: "nike2",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (2).png',
    },
    {
        id: "nike3",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (3).png',
    },
    {
        id: "nike4",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (4).png',
    },
    {
        id: "nike5",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (5).png',
    },
    {
        id: "nike6",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (6).png',
    },
    {
        id: "nike7",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (7).png',
    },
    {
        id: "nike8",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (8).png',
    },
    {
        id: "nike9",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (9).png',
    },
    {
        id: "nike10",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (10).png',
    },
    {
        id: "nike11",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (11).png',
    },
    {
        id: "nike12",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__1 (12).png',
    },
    {
        id: "nike13",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__5 (1).png',
    },
    {
        id: "nike14",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__5 (2).png',
    },
    {
        id: "nike15",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__5 (3).png',
    },
    {
        id: "nike16",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__5 (4).png',
    },
    {
        id: "nike17",
        name: 'Nike ',
        price: 150,
        image: '../public/nike/nike__5 (5).png',
    },
]
export const jordanProducts =[
    {
        id: "jordan1",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A1.png',
    },
    {
        id: "jordan2",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A2.png',
    },
    {
        id: "jordan3",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A3.png',
    },
    {
        id: "jordan4",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A4.png',
    },
    {
        id: "jordan5",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A5.png',
    },
    {
        id: "jordan6",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A6.png',
    },
    {
        id: "jordan7",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A7.png',
    },
    {
        id: "jordan8",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A8.png',
    },
    {
        id: "jordan9",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A9.png',
    },
    {
        id: "jordan10",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A10.png',
    },
    {
        id: "jordan11",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A11.png',
    },
    {
        id: "jordan12",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A12.png',
    },
    {
        id: "jordan13",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A13.png',
    },
    {
        id: "jordan14",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A14.png',
    },
    {
        id: "jordan15",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A15.png',
    },
    {
        id: "jordan16",
        name: 'Jordan ',
        price: 200,
        image: '../public/Jordan/A16.png',
    },
]